{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-glasso
  version: 1.8

source:
  fn: glasso_1.8.tar.gz
  url:
    - hhttps://cran.r-project.org/src/contrib/glasso_1.8.tar.gz

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('glasso')"           # [not win]
    - "\"%R%\" -e \"library('glasso')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=glasso
  license: GPL (>= 2)
  summary: 'Graphical lasso estimation of Gaussian graphical models'

  license_family: GPL2
